
package ClientFile;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerFile", targetNamespace = "http://ServerFile", wsdlLocation = "http://localhost:6231/MTLServer?wsdl")
public class ServerFile
    extends Service
{

    private final static URL SERVERFILE_WSDL_LOCATION;
    private final static WebServiceException SERVERFILE_EXCEPTION;
    private final static QName SERVERFILE_QNAME = new QName("http://ServerFile", "ServerFile");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:6231/MTLServer?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERFILE_WSDL_LOCATION = url;
        SERVERFILE_EXCEPTION = e;
    }

    public ServerFile() {
        super(__getWsdlLocation(), SERVERFILE_QNAME);
    }

    public ServerFile(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERFILE_QNAME, features);
    }

    public ServerFile(URL wsdlLocation) {
        super(wsdlLocation, SERVERFILE_QNAME);
    }

    public ServerFile(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERFILE_QNAME, features);
    }

    public ServerFile(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerFile(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServerInterface
     */
    @WebEndpoint(name = "ServerFilePort")
    public WebServerInterface getServerFilePort() {
        return super.getPort(new QName("http://ServerFile", "ServerFilePort"), WebServerInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServerInterface
     */
    @WebEndpoint(name = "ServerFilePort")
    public WebServerInterface getServerFilePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ServerFile", "ServerFilePort"), WebServerInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERFILE_EXCEPTION!= null) {
            throw SERVERFILE_EXCEPTION;
        }
        return SERVERFILE_WSDL_LOCATION;
    }

}
