
package ClientFile;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WebServerInterface", targetNamespace = "http://ServerFile/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServerInterface {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg6
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTRecord", targetNamespace = "http://ServerFile/", className = "ClientFile.CreateTRecord")
    @ResponseWrapper(localName = "createTRecordResponse", targetNamespace = "http://ServerFile/", className = "ClientFile.CreateTRecordResponse")
    @Action(input = "http://ServerFile/WebServerInterface/createTRecordRequest", output = "http://ServerFile/WebServerInterface/createTRecordResponse")
    public boolean createTRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSRecord", targetNamespace = "http://ServerFile/", className = "ClientFile.CreateSRecord")
    @ResponseWrapper(localName = "createSRecordResponse", targetNamespace = "http://ServerFile/", className = "ClientFile.CreateSRecordResponse")
    @Action(input = "http://ServerFile/WebServerInterface/createSRecordRequest", output = "http://ServerFile/WebServerInterface/createSRecordResponse")
    public boolean createSRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editRecord", targetNamespace = "http://ServerFile/", className = "ClientFile.EditRecord")
    @ResponseWrapper(localName = "editRecordResponse", targetNamespace = "http://ServerFile/", className = "ClientFile.EditRecordResponse")
    @Action(input = "http://ServerFile/WebServerInterface/editRecordRequest", output = "http://ServerFile/WebServerInterface/editRecordResponse")
    public boolean editRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "printRecord", targetNamespace = "http://ServerFile/", className = "ClientFile.PrintRecord")
    @ResponseWrapper(localName = "printRecordResponse", targetNamespace = "http://ServerFile/", className = "ClientFile.PrintRecordResponse")
    @Action(input = "http://ServerFile/WebServerInterface/printRecordRequest", output = "http://ServerFile/WebServerInterface/printRecordResponse")
    public boolean printRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecordCounts", targetNamespace = "http://ServerFile/", className = "ClientFile.GetRecordCounts")
    @ResponseWrapper(localName = "getRecordCountsResponse", targetNamespace = "http://ServerFile/", className = "ClientFile.GetRecordCountsResponse")
    @Action(input = "http://ServerFile/WebServerInterface/getRecordCountsRequest", output = "http://ServerFile/WebServerInterface/getRecordCountsResponse")
    public String getRecordCounts();

}
